# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0004_auto_20171103_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ScoreRankName',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc3b1ae-ee9c-11e7-9d55-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc3ffcf-ee9c-11e7-9a96-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc33c80-ee9c-11e7-84e5-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc33c81-ee9c-11e7-8635-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc426de-ee9c-11e7-935d-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc4c321-ee9c-11e7-8ddd-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc3d8c1-ee9c-11e7-b19a-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='Uuid',
            field=models.URLField(blank=True, default=b'5bc3d8c0-ee9c-11e7-be6a-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc38a9e-ee9c-11e7-8dd9-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='Progress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc27930-ee9c-11e7-b93a-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc2a041-ee9c-11e7-be75-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc2a040-ee9c-11e7-9b1d-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Evaluate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc31570-ee9c-11e7-b871-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Describe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc3638f-ee9c-11e7-95da-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc44df0-ee9c-11e7-b333-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc47500-ee9c-11e7-972c-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc49c0f-ee9c-11e7-8fcd-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc25221-ee9c-11e7-84b7-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc2ee61-ee9c-11e7-a378-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'5bc2c751-ee9c-11e7-8374-68f728892930', null=True),
        ),
    ]
