# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0005_auto_20180101_1034'),
        ('admina', '0006_auto_20180107_2009'),
    ]

    operations = [
    ]
