# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0007_merge_20180406_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ApplyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Apply_Message_set', to='admina.Apply'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae109f0-6f02-11e8-bae8-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae1580f-6f02-11e8-b68f-68f728892930', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae094c0-6f02-11e8-9355-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae094c1-6f02-11e8-86c4-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae17f21-6f02-11e8-802b-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae21b5e-6f02-11e8-8bb9-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae13101-6f02-11e8-b12a-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='Uuid',
            field=models.URLField(blank=True, default=b'fae13100-6f02-11e8-a561-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae0e2e1-6f02-11e8-a734-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fadfd16e-6f02-11e8-a3b6-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae01f8f-6f02-11e8-96d0-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fadff880-6f02-11e8-8a20-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae06db0-6f02-11e8-9a3d-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae0bbcf-6f02-11e8-ba8e-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae1a630-6f02-11e8-8038-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae1cd40-6f02-11e8-914c-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae1f451-6f02-11e8-897f-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fadf834f-6f02-11e8-9ac3-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae0469e-6f02-11e8-89a9-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'fae01f90-6f02-11e8-b87b-68f728892930', null=True),
        ),
    ]
