# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0009_auto_20180613_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df6204f-6f03-11e8-9693-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df6bc91-6f03-11e8-9541-68f728892930', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df5ab1e-6f03-11e8-9b50-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df5ab1f-6f03-11e8-aacd-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df6e3a1-6f03-11e8-8c4b-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df77fde-6f03-11e8-8132-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df66e71-6f03-11e8-9d53-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='Uuid',
            field=models.URLField(blank=True, default=b'2df66e70-6f03-11e8-bd69-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df5f940-6f03-11e8-afdc-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df4c0c0-6f03-11e8-84f9-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df50ede-6f03-11e8-9020-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df4e7cf-6f03-11e8-8316-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df55d00-6f03-11e8-8706-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df5d230-6f03-11e8-8ddc-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df70ab0-6f03-11e8-b4ba-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df731c0-6f03-11e8-a448-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df758d1-6f03-11e8-baed-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df42480-6f03-11e8-a0d1-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df535ef-6f03-11e8-b0a5-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'2df535ee-6f03-11e8-a9b5-68f728892930', null=True),
        ),
    ]
