# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0010_auto_20180613_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ScoreRankName',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b873c0f-6f03-11e8-88f8-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b87b140-6f03-11e8-bf48-68f728892930', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creation',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b86c6de-6f03-11e8-9230-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='creation2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b86edee-6f03-11e8-8101-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b87d84f-6f03-11e8-b3aa-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='helpapplication',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b884d81-6f03-11e8-89d8-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b878a30-6f03-11e8-8861-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='Uuid',
            field=models.URLField(blank=True, default=b'6b87631e-6f03-11e8-9b62-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b871501-6f03-11e8-94c3-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b862aa1-6f03-11e8-9c25-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='project2projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b8651b0-6f03-11e8-b9c8-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b862aa2-6f03-11e8-9357-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b869fcf-6f03-11e8-a565-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b871500-6f03-11e8-8f50-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b87ff61-6f03-11e8-afaf-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b882670-6f03-11e8-a1c9-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b884d80-6f03-11e8-a489-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b858e61-6f03-11e8-a025-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='user2userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b8678c1-6f03-11e8-a760-68f728892930', null=True),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='Uuid',
            field=models.UUIDField(blank=True, default=b'6b8678c0-6f03-11e8-85b7-68f728892930', null=True),
        ),
    ]
